name: flutter_instancy_2
description: This is a learning app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #region utils:
  add_2_calendar: ^3.0.1
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  flutter_breadcrumb: ^1.0.1
  flutter_onboard: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  font_awesome_flutter: ^10.6.0
  html: ^0.15.4
  jiffy: ^6.2.2
  linear_progress_bar: ^1.1.0
  logger: ^2.0.2+1
  open_file_plus: ^3.4.1
  path_provider: ^2.1.1
  readmore: ^2.2.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.2.2
  vector_math: ^2.1.4
  mime: ^1.0.4
  document_file_save_plus: ^2.0.0
  googleapis_auth: ^1.4.1
  google_mlkit_text_recognition: ^0.11.0
  speech_to_text: 6.5.1
  speech_to_text_platform_interface: 2.1.0
  just_audio: ^0.9.36
  rxdart: ^0.27.7
  video_thumbnail: ^0.5.3
  in_app_purchase: ^3.1.11
  confetti: ^0.7.0
  lottie: ^3.1.0
  xml: ^6.5.0
  shake: ^2.2.0
  #endregion

  #region State Management:
  provider: ^6.1.1
  #endregion

  #region File Operations:
  archive: ^3.4.9
  permission_handler: ^11.1.0     #TODO: Need IOS Setup
  #endregion

  #region File Download:
  flutter_downloader: ^1.11.6
  #endregion

  #region offline database:
  hive: ^2.2.3
  sqflite: ^2.3.0
  #endregion

  #region File Operations:
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  #endregion

  #region UI:
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.9
  material_design_icons_flutter: ^7.0.7296
  percent_indicator: ^4.2.3
  scrollable_positioned_list: ^0.3.8
  syncfusion_flutter_calendar: ^24.1.41
  syncfusion_flutter_charts: ^24.1.41
  stylish_bottom_bar: ^1.0.3

  #region Loaders:
  flutter_spinkit: ^5.2.0
  loading_animation_widget: ^1.2.0+4
  #endregion

  #region Popup Messages
  fluttertoast: ^8.2.4
  top_snackbar_flutter: ^3.1.0
  overlay_support: ^2.1.0
  #endregion

  #endregion

  #region Firebase:
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  #endregion

  #region Webview:
  flutter_inappwebview: ^6.0.0
  webviewx: ^0.2.2
  #endregion

  #region Media Players
  video_player: ^2.8.1
  camera: ^0.10.5+7
  #endregion

  #region PDF Operations
  printing: ^5.11.1
  pdf: ^3.10.7
  image: ^4.1.3
  #endregion

  flutter_chat_bot:
    git:
      url: https://Instancy@dev.azure.com/Instancy/Mobile%20Platform/_git/ChatBot
      ref: my_dev

  arcore_flutter_plugin:
    git:
      url: https://github.com/Rockstar95/arcore_flutter_plugin
      ref: master

dependency_overrides:
  intl: ^0.19.0
  uuid: ^4.3.1
  meta: ^1.11.0
  googleapis: ^12.0.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  http: ^1.1.2

flutter_icons:
  image_path: "assets/logo.png"
  image_path_android: "assets/logo.png"
  #  image_path: "assets/marketplaceicon.png"
  #  image_path_android: "assets/marketplaceicon.png"
  android: false # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: assets/Roboto-Medium.ttf
          weight: 500

    #          weight: 700
  assets:
    - assets/
    - assets/app-logo/
    - assets/js/
    - assets/images/
    - assets/onBoarding/
    - assets/socials/
    - assets/myLearning/
    - assets/catalog/
    - assets/sortIcons/
    - assets/lens_images/
    - lang/
    - assets/my_dashboard/
    - assets/lottie/
