name: flutter_instancy_2
description: This is a learning app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #region App Specific:
  flutter_launcher_icons: ^0.13.0
  #endregion

  #region utils:
  add_2_calendar: ^2.2.3
  connectivity_plus: ^2.3.9
  equatable: ^2.0.5
  flutter_breadcrumb: ^1.0.1
  flutter_onboard: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  font_awesome_flutter: ^10.2.1
  html: ^0.15.2
  intl: ^0.18.0
  jiffy: ^6.2.1
  linear_progress_bar: ^1.1.0
  logger: ^1.1.0
  open_file_plus: ^3.4.0
  path_provider: ^2.0.11
  readmore: ^2.2.0
  share_plus: ^7.0.0
  shared_preferences: ^2.0.15
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.1.6
  uuid: ^3.0.7
  vector_math: ^2.1.2
  mime: ^1.0.4
  document_file_save_plus: ^2.0.0
  googleapis: ^11.3.0
  googleapis_auth: ^1.4.1
  google_mlkit_text_recognition: ^0.10.0
  #endregion

  #region State Management:
  provider: ^6.0.4
  #endregion

  #region File Operations:
  archive: ^3.3.4
  permission_handler: ^10.2.0     #TODO: Need IOS Setup
  #endregion

  #region File Download:
  flutter_downloader: ^1.9.1
  #endregion

  #region offline database:
  hive: ^2.2.3
  sqflite: ^2.0.3+1
  #endregion

  #region File Operations:
  image_picker: ^1.0.1
  file_picker: ^5.3.3
  #endregion

  #region UI:
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  google_fonts: ^4.0.3
  carousel_slider: ^4.1.1
  flutter_speed_dial: ^6.2.0
  flutter_svg: ^2.0.2
  material_design_icons_flutter: ^6.0.7096
  scrollable_positioned_list: ^0.3.8
  syncfusion_flutter_calendar: ^22.2.10

  #region Loaders:
  flutter_spinkit: ^5.1.0
  loading_animation_widget: ^1.2.0+3
  shimmer: ^2.0.0
  #endregion

  #region Popup Messages
  fluttertoast: ^8.1.1
  top_snackbar_flutter: ^3.0.0
  overlay_support: ^2.1.0
  #endregion

  #endregion

  #region Firebase:
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.7.0
  firebase_messaging: ^14.1.1
  #endregion

  #region Social Login
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.6     #TODO: Need Android and IOS Setup
  #endregion

  #region Api Operations:
  http: ^0.13.5
  #endregion

  #region Webview:
  flutter_inappwebview: ^6.0.0-beta.22
  webviewx: ^0.2.1
  #endregion

  #region Media Players
  video_player: ^2.7.0
  camera: ^0.10.5+2
  #endregion

  #region PDF Operations
  printing: ^5.11.0
  pdf: ^3.10.4
  image: ^4.0.17
  #endregion

  flutter_chat_bot:
    git:
      url: https://github.com/bhpy247/chatBot
      ref: master

  arcore_flutter_plugin:
    git:
      url: https://github.com/Rockstar95/arcore_flutter_plugin
      ref: master


flutter_icons:
  # image_path: "assets/logo.png"
  # image_path_android: "assets/logo.png"
  #  image_path: "assets/marketplaceicon.png"
  #  image_path_android: "assets/marketplaceicon.png"
  image_path: "assets/logo.png"
  image_path_android: "assets/logo.png"
  android: false # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: assets/Roboto-Medium.ttf
          weight: 500

    #          weight: 700
  assets:
    - assets/
    - assets/js/
    - assets/images/
    - assets/onBoarding/
    - assets/socials/
    - assets/myLearning/
    - assets/catalog/
    - assets/sortIcons/
    - lang/
