enum InstancyContentActionsEnum {
  View,
  NA,
  Details,
  AddToMyLearning,
  Enroll,
  Join,
  Buy,
  IAmInterested,
  ContactUs,

  //Secondary Actions
  AddToWishlist,
  RemoveFromWishlist,
  Delete,
  Archive,
  Unarchive,
  Report,
  Notes,
  RecommendTo,
  Download,
  ViewCertificate,
  SetComplete,
  AddToWaitList,
  CancelEnrollment,
  ViewResources,
  AddToCalender,
  ViewQRCode,
  ViewSessions,
  Reschedule,
  ReEnrollmentHistory,
  ShareToConnections,
  ShareWithPeople,
  Share,
  Play,
  ViewRecording,

  // addToCalender,
  // relatedContent,
  // cancelEnrollment,
  // reschedule,
  // qrCode,
  // eventRecording,
  // sendViaEmail,
}

enum InstancyContentScreenType {
  Catalog,
  MyLearning,
}