class DiscussionTopicUiActionParameterModel {
  final String contentID;
  final String name;
  final String createdDate;
  final String longDescription;
  final String latestReplyBy;
  final String author;
  final String uploadFileName;
  final String updatedTime;
  final String createdTime;
  final String modifiedUserName;
  final String uploadedImageName;
  final String topicImageUploadName;
  final String topicUploadIconPath;
  final String topicUserProfile;
  final bool isPin;
  final String comments;
  final String likedUserList;
  final int CreatedUserID;
  final int noOfReplies;
  final int noOfViews;
  final int pinID;
  final int likes;
  final bool likeState;
  final bool CreateNewTopic;
  final bool AllowPin;
  final bool AllowShare;
  final bool AttachFile;
  final bool LikePosts;

  const DiscussionTopicUiActionParameterModel({
    this.contentID = "",
    this.name = "",
    this.createdDate = "",
    this.CreatedUserID = 0,
    this.noOfReplies = 0,
    this.noOfViews = 0,
    this.longDescription = "",
    this.latestReplyBy = "",
    this.author = "",
    this.uploadFileName = "",
    this.updatedTime = "",
    this.createdTime = "",
    this.modifiedUserName = "",
    this.uploadedImageName = "",
    this.topicImageUploadName = "",
    this.topicUploadIconPath = "",
    this.likes = 0,
    this.topicUserProfile = "",
    this.isPin = false,
    this.pinID = 0,
    this.comments = "",
    this.likedUserList = "",
    this.likeState = false,
    this.CreateNewTopic = false,
    this.AllowPin = false,
    this.AllowShare = false,
    this.AttachFile = false,
    this.LikePosts = false,
  });
}
