class CatalogUIActionParameterModel {
  final int objectTypeId;
  final int mediaTypeId;
  final int ViewType;
  final int eventScheduleType;
  final int isWishlistContent;
  final bool isWishlistMode;
  final bool hasRelatedContents;
  final bool isContentEnrolled;
  final bool bit4;
  final bool eventRecording;
  final String ViewLink;
  final String AddLink;
  final String BuyNowLink;
  final String EnrollNowLink;
  final String TitleExpired;
  final String DetailsLink;
  final String cancelEventLink;
  final String eventStartDatetime;
  final String eventenddatetime;
  final String InstanceEventReSchedule;
  final String ReEnrollmentHistory;
  final String waitListLink;
  final String RecommendedLink;
  final String suggestToConnectionsLink;
  final String suggestWithFriendLink;
  final String shareLink;
  final String AddToWishlist;
  final String RemoveFromWishList;
  final String RelatedContentLink;
  final String IsRelatedcontent;
  final String ShareToRecommend;
  final String ContentName;

  const CatalogUIActionParameterModel({
    this.objectTypeId = 0,
    this.mediaTypeId = 0,
    this.ViewType = 0,
    this.eventScheduleType = 0,
    this.isWishlistContent = 0,
    this.isWishlistMode = false,
    this.hasRelatedContents = false,
    this.isContentEnrolled = false,
    this.bit4 = false,
    this.eventRecording = false,
    this.ViewLink = "",
    this.AddLink = "",
    this.BuyNowLink = "",
    this.EnrollNowLink = "",
    this.TitleExpired = "",
    this.DetailsLink = "",
    this.cancelEventLink = "",
    this.eventStartDatetime = "",
    this.eventenddatetime = "",
    this.InstanceEventReSchedule = "",
    this.ReEnrollmentHistory = "",
    this.waitListLink = "",
    this.RecommendedLink = "",
    this.suggestToConnectionsLink = "",
    this.suggestWithFriendLink = "",
    this.shareLink = "",
    this.AddToWishlist = "",
    this.RemoveFromWishList = "",
    this.RelatedContentLink = "",
    this.IsRelatedcontent = "",
    this.ShareToRecommend = "",
    this.ContentName = "",
  });
}