import '../../../utils/parsing_helper.dart';

class NewCourseListDTOModel {
  String authorDisplayName = "";
  String contentAuthorDisplayname = "";
  String contentID = "";
  String contentType = "";
  String contentTypeThumbNail = "";
  String thumbnailIconPath = "";
  String name = "";
  int objectTypeID = 0;
  int mediaTypeID = 0;
  String shortDescription = "";
  String thumbnailImagePath = "";
  String strThumbUrl = "";
  String salesPrice = "";
  int viewType = 0;
  double ratingID = 0;
  int totalRatings = 0;
  String currency = "";
  String detailsLink = "";
  int createdContentUserID = 0;
  String salepricestrikeoff = "";
  String creditScore = "";
  bool showratings = false;
  int enrollmentLimit = 0;
  int noofUsersEnrolled = 0;
  int availableSeats = 0;
  bool eventNotStarted = false;
  String buildingName = "";
  int eventType = 0;
  int eventScheduleType = 0;
  int categoryID = 0;
  String assignedDate = "";
  String thumbnailVideoPath = "";
  String duration = "";
  String durationWithHMSplite = "";
  String eventStartDateTime = "";
  String eventEndDateTime = "";
  String daysRemaining = "";
  String backgroundcolor = "";
  String fontcolor = "";
  String gradient1 = "";
  String gradient2 = "";
  String gradientColor = "";
  String viewLink = "";

  NewCourseListDTOModel(
      {this.authorDisplayName = "",
        this.contentAuthorDisplayname = "",
        this.contentID = "",
        this.contentType = "",
        this.contentTypeThumbNail = "",
        this.thumbnailIconPath = "",
        this.name = "",
        this.objectTypeID = 0,
        this.mediaTypeID = 0,
        this.shortDescription = "",
        this.thumbnailImagePath = "",
        this.strThumbUrl = "",
        this.salesPrice = "",
        this.viewType = 0,
        this.ratingID = 0,
        this.totalRatings = 0,
        this.currency = "",
        this.detailsLink = "",
        this.createdContentUserID = 0,
        this.salepricestrikeoff = "",
        this.creditScore = "",
        this.showratings = false,
        this.enrollmentLimit = 0,
        this.noofUsersEnrolled = 0,
        this.availableSeats = 0,
        this.eventNotStarted = false,
        this.buildingName = "",
        this.eventType = 0,
        this.eventScheduleType = 0,
        this.categoryID = 0,
        this.assignedDate = "",
        this.thumbnailVideoPath = "",
        this.duration = "",
        this.durationWithHMSplite = "",
        this.eventStartDateTime = "",
        this.eventEndDateTime = "",
        this.daysRemaining = "",
        this.backgroundcolor = "",
        this.fontcolor = "",
        this.gradient1 = "",
        this.gradient2 = "",
        this.gradientColor = "",
        this.viewLink = ""});

  NewCourseListDTOModel.fromJson(Map<String, dynamic> json) {
    authorDisplayName = ParsingHelper.parseStringMethod(json['AuthorDisplayName']);
    contentAuthorDisplayname = ParsingHelper.parseStringMethod(json['ContentAuthorDisplayname']);
    contentID = ParsingHelper.parseStringMethod(json['ContentID']);
    contentType = ParsingHelper.parseStringMethod(json['ContentType']);
    contentTypeThumbNail = ParsingHelper.parseStringMethod(json['ContentTypeThumbNail']);
    thumbnailIconPath = ParsingHelper.parseStringMethod(json['ThumbnailIconPath']);
    name = ParsingHelper.parseStringMethod(json['Name']);
    objectTypeID = ParsingHelper.parseIntMethod(json['ObjectTypeID']);
    mediaTypeID = ParsingHelper.parseIntMethod(json['MediaTypeID']);
    shortDescription = ParsingHelper.parseStringMethod(json['ShortDescription']);
    thumbnailImagePath = ParsingHelper.parseStringMethod(json['ThumbnailImagePath']);
    strThumbUrl = ParsingHelper.parseStringMethod(json['strThumbUrl']);
    salesPrice = ParsingHelper.parseStringMethod(json['salesPrice']);
    viewType = ParsingHelper.parseIntMethod(json['viewType']);
    ratingID = ParsingHelper.parseDoubleMethod(json['RatingID']);
    totalRatings = ParsingHelper.parseIntMethod(json['TotalRatings']);
    currency = ParsingHelper.parseStringMethod(json['currency']);
    detailsLink = ParsingHelper.parseStringMethod(json['DetailsLink']);
    createdContentUserID = ParsingHelper.parseIntMethod(json['CreatedContentUserID']);
    salepricestrikeoff = ParsingHelper.parseStringMethod(json['salepricestrikeoff']);
    creditScore = ParsingHelper.parseStringMethod(json['CreditScore']);
    showratings = ParsingHelper.parseBoolMethod(json['showratings']);
    enrollmentLimit = ParsingHelper.parseIntMethod(json['EnrollmentLimit']);
    noofUsersEnrolled = ParsingHelper.parseIntMethod(json['NoofUsersEnrolled']);
    availableSeats = ParsingHelper.parseIntMethod(json['AvailableSeats']);
    eventNotStarted = ParsingHelper.parseBoolMethod(json['EventNotStarted']);
    buildingName = ParsingHelper.parseStringMethod(json['BuildingName']);
    eventType = ParsingHelper.parseIntMethod(json['EventType']);
    eventScheduleType = ParsingHelper.parseIntMethod(json['EventScheduleType']);
    categoryID = ParsingHelper.parseIntMethod(json['CategoryID']);
    assignedDate = ParsingHelper.parseStringMethod(json['AssignedDate']);
    thumbnailVideoPath = ParsingHelper.parseStringMethod(json['ThumbnailVideoPath']);
    duration = ParsingHelper.parseStringMethod(json['Duration']);
    durationWithHMSplite = ParsingHelper.parseStringMethod(json['DurationWithHMSplite']);
    eventStartDateTime = ParsingHelper.parseStringMethod(json['EventStartDateTime']);
    eventEndDateTime = ParsingHelper.parseStringMethod(json['EventEndDateTime']);
    daysRemaining = ParsingHelper.parseStringMethod(json['DaysRemaining']);
    backgroundcolor = ParsingHelper.parseStringMethod(json['backgroundcolor']);
    fontcolor = ParsingHelper.parseStringMethod(json['fontcolor']);
    gradient1 = ParsingHelper.parseStringMethod(json['Gradient1']);
    gradient2 = ParsingHelper.parseStringMethod(json['Gradient2']);
    gradientColor = ParsingHelper.parseStringMethod(json['GradientColor']);
    viewLink = ParsingHelper.parseStringMethod(json['ViewLink']);
  }

  Map<String, dynamic> toMap() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['AuthorDisplayName'] = authorDisplayName;
    data['ContentAuthorDisplayname'] = contentAuthorDisplayname;
    data['ContentID'] = contentID;
    data['ContentType'] = contentType;
    data['ContentTypeThumbNail'] = contentTypeThumbNail;
    data['ThumbnailIconPath'] = thumbnailIconPath;
    data['Name'] = name;
    data['ObjectTypeID'] = objectTypeID;
    data['MediaTypeID'] = mediaTypeID;
    data['ShortDescription'] = shortDescription;
    data['ThumbnailImagePath'] = thumbnailImagePath;
    data['strThumbUrl'] = strThumbUrl;
    data['salesPrice'] = salesPrice;
    data['viewType'] = viewType;
    data['RatingID'] = ratingID;
    data['TotalRatings'] = totalRatings;
    data['currency'] = currency;
    data['DetailsLink'] = detailsLink;
    data['CreatedContentUserID'] = createdContentUserID;
    data['salepricestrikeoff'] = salepricestrikeoff;
    data['CreditScore'] = creditScore;
    data['showratings'] = showratings;
    data['EnrollmentLimit'] = enrollmentLimit;
    data['NoofUsersEnrolled'] = noofUsersEnrolled;
    data['AvailableSeats'] = availableSeats;
    data['EventNotStarted'] = eventNotStarted;
    data['BuildingName'] = buildingName;
    data['EventType'] = eventType;
    data['EventScheduleType'] = eventScheduleType;
    data['CategoryID'] = categoryID;
    data['AssignedDate'] = assignedDate;
    data['ThumbnailVideoPath'] = thumbnailVideoPath;
    data['Duration'] = duration;
    data['DurationWithHMSplite'] = durationWithHMSplite;
    data['EventStartDateTime'] = eventStartDateTime;
    data['EventEndDateTime'] = eventEndDateTime;
    data['DaysRemaining'] = daysRemaining;
    data['backgroundcolor'] = backgroundcolor;
    data['fontcolor'] = fontcolor;
    data['Gradient1'] = gradient1;
    data['Gradient2'] = gradient2;
    data['GradientColor'] = gradientColor;
    data['ViewLink'] = viewLink;
    return data;
  }
}